#!/usr/bin/env python
# -*- coding: utf-8

NAME_REPLACES = {
    'Adriano Jose Alves Moreira': 'Adriano José Alves Moreira',
    'Antonio Chaves Medeiros': 'António Chaves Medeiros',
    'Antonio Costa de Albuquerque de Sousa Lara': 'António Costa de Albuquerque de Sousa Lara',
    'Antonio Domingues de Azevedo': 'António Domingues de Azevedo',
    'Antonio Joaquim Bastos Marques Mendes': 'António Joaquim Bastos Marques Mendes',
    'Antonio Jorge de Figueiredo Lopes': 'António Jorge de Figueiredo Lopes',
    'Antonio José Caeiro da Motta Veiga': 'António José Caeiro da Motta Veiga',
    'Antonio Moreira Barbosa de Melo': 'António Moreira Barbosa de Melo',
    'Antonio Poppe Lopes Cardoso': 'António Poppe Lopes Cardoso',
    "António D'orey Capucho": "António D'Orey Capucho",
    'Arlindo da Silva Andre Moreira': 'Arlindo da Silva André Moreira',
    'Eurico Jose Palheiros de Carvalho Figueiredo': 'Eurico José Palheiros de Carvalho Figueiredo',
    'Fernando Jose Antunes Gomes Pereira': 'Fernando José Antunes Gomes Pereira',
    'Fernando Jose da Costa': 'Fernando José da Costa',
    'Fernando Jose Russo Roque Correia Afonso': 'Fernando José Russo Roque Correia Afonso',
    'Francisco Joao Bernardino da Silva': 'Francisco João Bernardino da Silva',
    'Jaime Adalberto Simoes Ramos': 'Jaime Adalberto Simões Ramos',
    'Joao Eduardo Coelho Ferraz de Abreu': 'João Eduardo Coelho Ferraz de Abreu',
    'Jose Albino da Silva Peneda': 'José Albino Silva Peneda',
    'Jose de Oliveira Costa': 'José de Oliveira Costa',
    'José Luis Nogueira de Brito': 'José Luís Nogueira de Brito',
    'Jose Manuel Oliveira Gameiro dos Santos': 'José Manuel Oliveira Gameiro dos Santos',
    'Jose Pereira Lopes': 'José Pereira Lopes',
    'Leonardo Eugenio Ribeiro de Almeida': 'Leonardo Eugénio Ribeiro de Almeida',
    'Luis Fernando de Mira Amaral': 'Luís Fernando de Mira Amaral',
    'Manuel Antonio dos Santos': 'Manuel António dos Santos',
    'Maria Luisa Lourenço Ferreira': 'Maria Luísa Lourenço Ferreira',
    'Maria Teresa Doria Santa Clara Gomes': 'Maria Teresa Dória Santa Clara Gomes',
}

SHORTNAME_REPLACES = {
    'António Amaro': 'António Leitão Amaro',
    'Maria Gabriela Canavilhas': 'Gabriela Canavilhas',
    'José Matos Rosa': 'José de Matos Rosa',
    'José Matos Correia': 'José de Matos Correia',
    'Maria da Conceição Pereira': 'Maria Conceição Pereira',
    'Maria Helena André': 'Helena André',
    'Duarte Marques': 'Duarte Filipe Marques',
    'Maria Francisca Almeida': 'Francisca Almeida',
    'Francisco Assis': 'Francisco de Assis',
    'Paulo Baptista Santos': 'Paulo Batista Santos',
    'João Antunes': 'João Figueiredo',
    'Carlos Gonçalves': 'Carlos Alberto Gonçalves',
    'Ana Catarina Mendonça Mendes': 'Ana Catarina Mendonça',
    'António Peixoto': 'Carlos Peixoto',
    'Carlos Amorim': 'Carlos Abreu Amorim',
    'João Mota Amaral': 'Mota Amaral',
    'Helder Amaral': 'Hélder Amaral',
    'Heitor de Sousa': 'Heitor Sousa',
    'Pedro do ó Ramos': 'Pedro do Ó Ramos',
    'Isabel Moreira': 'Isabel Alves Moreira',
    'Carlos Silva': 'Carlos Santos Silva',
    'Álvaro Castelo Branco': 'Álvaro Castello-Branco',
    "Filipe Lobo D' Ávila": "Filipe Lobo d'Ávila",
    'Regina Bastos': 'Regina Ramos Bastos',
    'Maria Leonor Beleza': 'Leonor Beleza',
    'Maria Antónia de Almeida Santos': 'Maria Antónia Almeida Santos',
    'Maria das Mercês Borges': 'Maria das Mercês Soares',
    'Eduardo Ferro Rodrigues': 'Ferro Rodrigues',
    'Rosa Maria Bastos Albernaz': 'Rosa Maria Albernaz',
    'Domicilia Costa': 'Domicília Costa',
}
